ALTER TABLE deuda ALTER COLUMN "userId" DROP NOT NULL;
ALTER TABLE deuda ADD COLUMN IF NOT EXISTS "nombreCliente" VARCHAR(200);
ALTER TABLE deuda ADD COLUMN IF NOT EXISTS "telefonoCliente" VARCHAR(30);
